### ISSUE TITLE
Device descriptor request failure

### ISSUE THREAD

**Issue by lk-davidegironi** [WangXuan95/FPGA-USB-Device#10]
Hello Wang,
thanks for sharing your project. I'm already using your FT245 library. FTDI is great but I would like to use direct USB.
I've a problem running your IP. Device is not recognised.
I've connected it using 40cm USB cable cut and soldered to my FPGA dev pins.
I'm working on the Tang Primer 20k.
I've implemented your fpga_top_usb_audio on a GoWin based Tang Primer 20k.
No timing issues.
PLL 60Mhz generated clock.

On Windows 10 (using a USB HUB, and straight to the PC ) i get the error: Matching Device Id: USB\DEVICE_DESCRIPTOR_FAILURE
On Linux Ubuntu (straight to the motherboard USB), device is not recognised. Find it the wireshark capture attached.
[usb_wireshark.zip](https://github.com/WangXuan95/FPGA-USB-Device/files/12028567/usb_wireshark.zip)
Don't know how to solve this, any suggestion appreciated.

Thanks.

top module below:
```
module top
(
    input  wire sys_clk,
    input  wire sys_rst_n,
    output wire usb_dp_pull,  // connect to USB D+ by an 1.5k resistor
    inout wire usb_d_p,       // connect to USB D+
    inout wire usb_d_n
);

    // Clock generator
    wire clk;
    wire clkpll;
    assign clk = clkpll;
    wire clk_lock;
    pll2 pll2_inst (
        .clkin(sys_clk),
        .lock(clk_lock),
        .clkout(clkpll)
    );

    // System reset generator
    wire rst;
    assign rst = rst_reg;
	reg rst_reg;
	localparam RST_WIDTH = 10;
    reg [RST_WIDTH-1:0] rst_cnt;
	initial
	begin
		rst_cnt = 1;
	end
    always @(posedge clk)
    begin
        if(~sys_rst_n || ~clk_lock)
        begin
            rst_reg <= 1'b1;
            rst_cnt <= 1;
        end
        else if(rst_cnt != 0)
        begin
            rst_reg <= 1'b1;
            rst_cnt <= rst_cnt + 1;
        end
        else
            rst_reg <= 1'b0;
    end

    wire usb_rstn;
    wire [15:0] audio_l, audio_r;
    usb_audio_top #(
        .DEBUG("FALSE")
    ) u_usb_audio (
        .clk(clk),
        .rstn(~rst),
        // USB signals
        .usb_dp_pull(usb_dp_pull),
        .usb_dp(usb_d_p),
        .usb_dn(usb_d_n),
        // USB reset output
        .usb_rstn(usb_rstn),   // 1: connected , 0: disconnected (when USB cable unplug, or when system reset (rstn=0))
        // user data : audio output (host-to-device, such as a speaker), and audio input (device-to-host, such as a microphone).
        .audio_en(),
        .audio_lo(audio_l),   // left-channel output : 16-bit signed integer, which will be valid when audio_en=1
        .audio_ro(audio_r),   // right-channel output: 16-bit signed integer, which will be valid when audio_en=1
        .audio_li(audio_l),   // left-channel input  : 16-bit signed integer, which will be sampled when audio_en=1
        .audio_ri(audio_r),   // right-channel input : 16-bit signed integer, which will be sampled when audio_en=1
        // debug output info, only for USB developers, can be ignored for normally use
        .debug_en(),
        .debug_data(),
        .debug_uart_tx(uart_tx)
    );

endmodule
```

constraints below
```
IO_LOC "sys_clk" H11;
IO_PORT "sys_clk" IO_TYPE=LVCMOS33 PULL_MODE=NONE;
IO_LOC "sys_rst_n" T2;
IO_PORT "sys_rst_n" IO_TYPE=LVCMOS33;
IO_LOC "usb_dp_pull" A13;
IO_PORT "usb_dp_pull" IO_TYPE=LVCMOS33 PULL_MODE=DOWN DRIVE=12;
IO_LOC "usb_d_p" G11,H12;
IO_PORT "usb_d_p" IO_TYPE=LVCMOS33D;
```

**Comment by ExcielAT** [comment]
Check resistor connection.

**Comment by lk-davidegironi** [comment]
Thanks!
Seems ok to me.

I have 1k5 between G11 and A13 (usb_d_p and usb_dp_pull).
G11 connected to D+, H12 to D-, GND to GND (usb wiring of the connector like the picture below). USB VCC is not connected.
![usb_wiring](https://github.com/WangXuan95/FPGA-USB-Device/assets/90449776/901fc5ac-d552-48d1-85af-d7ab7f2213d0)

Below my actual hardware:
![pro-B4R6sYNd](https://github.com/WangXuan95/FPGA-USB-Device/assets/90449776/fa3d94b0-08dc-4caf-ad25-ddcbb7fb0c9f)

**Comment by WangXuan95** [comment]
Hello,

In constraints, did you forget to assign a pin for `usb_d_n` ? I've seen that you assign `G11` and `H12` for `usb_d_p` . Is this a differential pair constraint? (I'm not familiar with Gaoyun FPGA). Note that although D+ D- is a de facto differential pair, in this FPGA design we shouldn't regard it as a differential pair, but as two independent common IOs. So the correct constraints might be:
```
IO_LOC "usb_d_p" G11;
IO_PORT "usb_d_p" IO_TYPE=LVCMOS33D;
IO_LOC "usb_d_n" H12;
IO_PORT "usb_d_n" IO_TYPE=LVCMOS33D;
```

**Comment by lk-davidegironi** [comment]
Thanks @WangXuan95 
It's a "weird" syntax of the GoWin engine.
I can set it as both LVCMOS33, not both LVCMOS33D - cause the D on the first pin takes the relative negative differential. Like so:
```
IO_LOC "usb_d_p" G11;
IO_PORT "usb_d_p" IO_TYPE=LVCMOS33;
IO_LOC "usb_d_n" H12;
IO_PORT "usb_d_n" IO_TYPE=LVCMOS33;
```
In any way synthesis is the same, they are synthetized as two IOBUF (https://www.gowinsemi.com/upload/database_doc/39/document/5bfcff2ce0b72.pdf) - see Capture below:
![Capture](https://github.com/WangXuan95/FPGA-USB-Device/assets/90449776/846babed-51ae-4419-a631-d5e7b9147d7a)

**Comment by WangXuan95** [comment]
Fine, it seems that there are no issues on constraint of `usb_d_n` .

It seems that `usb_dp_pull` have pulled-up, so that the host detected it and try to request the descriptor, but it fails. If USB D+ is not pulled-up, the host cannot even start to request descriptor (there will be no any actions on Host PC).

There's a method to confirm this: Plug the USB to Host PC (we get a descriptor failure). Then reset the FPGA design by pull-down `sys_rst_n` (e.g. , press the button). This will let `usb_dp_pull` pull-down so that the Host will regard the USB unplugged. Then we release `sys_rst_n` to 1, the Host PC will re-report a descriptor failure.

If the phenomenon does not match the above, the problem may be elsewhere.

For the solution, now I have no idea. Maybe you can:

* Check whether the 60MHz clock is working
* Try to not use `PULL_MODE=DOWN` on `usb_dp_pull`. Since `usb_dp_pull` will only be `1` or `0` , but not `z` . So there is no sense to use the internal pulling.
* Use a shorter USB cable
* Use other FPGA (Xilinx, Altera, etc.) for testing.

**Comment by ExcielAT** [comment]
Hi.
I suggest you to check reset conditions, remember reset for this module is active low

In the code cannot be distinguished very well these conditions.

**Comment by lk-davidegironi** [comment]
Thanks,

Tried this:
 - there's a method to confirm this: Plug the USB to Host PC (we get a descriptor failure): Done, confirm the desc. failure
 - Then reset the FPGA design by pull-down sys_rst_n (e.g. , press the button)This will let usb_dp_pull pull-down so that the Host will regard the USB unplugged: Confirm: : It disappear from Device Manager (see Capture_rst1) ![Capture_rst1](https://github.com/WangXuan95/FPGA-USB-Device/assets/90449776/91004fc3-6af2-4867-98b8-8648f6d80d46)
 - Then we release sys_rst_n to 1, the Host PC will re-report a descriptor failure: No, can not see it anymore. To see it again I have to re-upload the fpga binary, OR detach and plug in again the USB. Fpga status like below (Capture_rst2) ![Capture_rst2](https://github.com/WangXuan95/FPGA-USB-Device/assets/90449776/94454ab7-df6f-4e76-80d9-fa1bab345085)

So, there's something with the pull pin?

Anyway, other tests done:

- Clock confirmed, divided by 32 with a toggle output is 937.49, so 937.49*32*2 = 59999.36
- I've try usb_dp_pull without PULL_MODE, with PULL_MODE=NONE,  with PULL_MODE=UP,  with PULL_MODE=DOWN. No difference
- Tried a shorter cable with no luck
- I can try a Xilinx Zynq based, but I'm going on vacation tomorrow :) I'll try when I'll be back

**Comment by WangXuan95** [comment]
Okay, it looks like we're really unlucky today.
Also, don't forget to check for faulty soldering and poor contact issues.
Looking forward to your results tomorrow

**Comment by lk-davidegironi** [comment]
Thanks!
I've not understand this:
You tell me 

> Then we release sys_rst_n to 1, the Host PC will re-report a descriptor failure

 This does not happen to me. Is this something I can relate to the pullup pin so?

**Comment by WangXuan95** [comment]
No, The specific reason for this phenomenon cannot be determined yet. But it increase the likelihood of dummy problems (such as solder and connection problems).

On the contrary, if everything goes as I expected (after releasing the reset, the Host PC reports a "descriptor error" again), then I will be even more suspicious that there is a bug in my USB module code. That will be even more troublesome.

**Comment by lk-davidegironi** [comment]
Get it... so. At first I'll check with another FPGA, as soon as I can, and let you know.

**Comment by ExcielAT** [comment]
Also try to isolate the module in an individual design. A rare problem i had once was realted with power banks. So by isolating the io pins on a different IO bank solution was achieved. Target device was TR4 by Altera.

**Comment by lk-davidegironi** [comment]
Thanks! It's yet a sample individual design with just that pins on same bank used. But I'll check it in deep.

**Comment by lk-davidegironi** [comment]
Thanks Wang! Case closed.
I've tested your code a dev PCB I design, the problem with the other board was the cables.
I'm trying now to benchmark the USB Serial. Seems to get 7.9Mbps, sounds right to you?
To benchmark the board I write a simple test problem in C under windows that sends 1000 packes of 1000 bytes each and read it back.

**Comment by lk-davidegironi** [comment]
Think I get this. It's about microframe and frame.
On USB 2.0 low speed and full speed latency is 1 ms due to frame timing.
On USB 2.0 high speed is 125 µs due to microframes timinig.
https://en.wikipedia.org/wiki/USB_communications
