### ISSUE TITLE
USB主时钟可以做48MHz的吗

### ISSUE THREAD

**Issue by wwjabc** [WangXuan95/FPGA-USB-Device#11]
有些FPGA性能不是很高，USB跑60MHz过高了一点。

**Comment by WangXuan95** [comment]
你好，
首先，别忘了给我的github点star和follow。
我这个代码并不支持 48MHz 时钟的，因为我是5分频的。理论上改成4分频就能支持 48MHz ，但需要改很多地方，愿意花时间的话你可以自己改改。
另外，你的意思是 60MHz 导致在某些 FPGA 上时序不收敛吗？我觉得不至于，我这个代码测了，在Altera Cyclone IV E 的最慢速率的器件上，fmax都能达到 109MHz 。你那里如果不收敛的话，是不是用的FPGA型号太旧了？




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangXuan95/FPGA-USB-Device"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 下午4:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WangXuan95/FPGA-USB-Device] USB主时钟可以做48MHz的吗 (Issue #11)





 
有些FPGA性能不是很高，USB跑60MHz过高了一点。
