### ISSUE TITLE
Always on 

### ISSUE THREAD

**Issue by czhou1972** [WangXuan95/FPGA-USB-Device#14]
Hi,
I might have done something wrong. The (Windows) PC gives dp/dn at 1.5M rate which is slow speed. The 1.5K resister is connected between dp+ and dp_pll. Any suggestion? Thank you

**Comment by WangXuan95** [comment]
Hi,
How do you know that the windows PC enters 1.5M (low-speed)? By viewing any USB softwares?
My IP do not support 1.5M low-speed, but only support 12M full-speed.
So is the USB device successfully recongnized?
Could you show your circuit connection?

**Comment by czhou1972** [comment]
Thanks for your reply. I just identified the cause for entering into low speed mode: the dp_pull was wrongly connected with dn, instead of dp. 

Much appreciated for what you have done. Amazing work. Thank you.

**Comment by WangXuan95** [comment]
Ok, that's fine.
feel free to ask me if you meet more questions.
If you like my repo, please star it.
