### ISSUE TITLE
USB Low-Speed support?

### ISSUE THREAD

**Issue by epsilon537** [WangXuan95/FPGA-USB-Device#17]
Have you considered adding USB Low-Speed support? That's a step back from Full-Speed of course, but it would be great if could use your USB device core in combination with a USB HID Host that's only low-speed capable. I think it's still common for low-end USB HID keyboard and mouse devices to be USB Low-Speed.

**Comment by WangXuan95** [comment]
A complete USB 1.1 device should indeed support both Full-Speed and Low-Speed, but I currently don't have time to do this.

It is indeed common for devices that only support LS, such as keyboards and mice. However, there are not many hosts that only support LS anymore, maybe only some very old computers, and This project is a USB device, so I don't think it's very necessary to support LS.

**Comment by epsilon537** [comment]
Understood. Thanks for the quick response.
