### ISSUE TITLE
每个example占用的fpga资源方不方便给一个表？

### ISSUE THREAD

**Issue by 1847123212** [WangXuan95/FPGA-USB-Device#6]
每个example占用fpga多少资源，比如多少le，多钱ramblock什么的

**Comment by WangXuan95** [comment]
下表是 6 个 example 在 Altera Cyclone IV EP4CE6E22C8 上占用的资源量，该数据由 Quartus 13.1 软件综合后给出。

|  Example Name               | Total logic element | Total Registers | Total Memory Bits |
| :--:                                    | :--:                          | :--:                    | :--:                          |
| fpga_top_usb_audio        | 1009                       | 446                  | 32768                     |
| fpga_top_usb_camera     | 995                         | 385                  | 0                             |
| fpga_top_usb_disk          | 1229                        | 630                  | 196608                  |
| fpga_top_usb_keyboard  | 903                         | 396                  | 0                             |
| fpga_top_usb_serial         | 783                        | 341                   | 8192                      |
| fpga_top_usb_serial2       | 883                        | 374                  | 16384                     |

**Comment by 1847123212** [comment]
十分感谢！
